In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE, ADASYN
import random
from random import sample
from sklearn.ensemble import RandomForestClassifier,BaggingClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn import model_selection
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold,GridSearchCV
from sklearn import model_selection

In [2]:
df=pd.read_csv("C:/Users/Arun/Downloads/aps_failure_training_set.csv")
test_df=pd.read_csv("C:/Users/Arun/Downloads/aps_failure_test_set.csv")

# EDA for Training Data:

In [3]:
df.head()

class  aa_000 ab_000      ac_000 ad_000 ae_000 af_000 ag_000 ag_001 ag_002  \
0   neg   76698     na  2130706438    280      0      0      0      0      0   
1   neg   33058     na           0     na      0      0      0      0      0   
2   neg   41040     na         228    100      0      0      0      0      0   
3   neg      12      0          70     66      0     10      0      0      0   
4   neg   60874     na        1368    458      0      0      0      0      0   

   ...     ee_002  ee_003  ee_004  ee_005  ee_006  ee_007  ee_008 ee_009  \
0  ...    1240520  493384  721044  469792  339156  157956   73224      0   
1  ...     421400  178064  293306  245416  133654   81140   97576   1500   
2  ...     277378  159812  423992  409564  320746  158022   95128    514   
3  ...        240      46      58      44      10       0       0      0   
4  ...     622012  229790  405298  347188  286954  311560  433954   1218   

  ef_000 eg_000  
0      0      0  
1      0      0  
2      0      0  
3      4     32  
4      0      0  

[5 rows x 171 columns]

In [4]:
#converting Class to numericals
df['class']=df['class'].map({'neg':0,'pos':1})

In [5]:
#removing and replacing na with np.NaN:
df.replace(to_replace='na',value=np.NaN,inplace=True)

In [37]:
df.shape

(60000, 162)

In [7]:
df=df.dropna(axis=1,thresh=36000) #Dropping column which don't have atleast 60% of data or 40% of NaN

In [8]:
x1=df.drop(['class'],1)
y1=df['class']

In [9]:
#imputation:
from sklearn.preprocessing import Imputer
impute_median = Imputer(missing_values= np.nan, strategy='median')
train_data = pd.DataFrame(impute_median.fit_transform(x1),columns=x1.columns)

C:\Users\Arun\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [10]:
train_data['class']=y1

In [11]:
train_data['class'].dtype

dtype('int64')

In [12]:
x2=train_data.drop(['class'],1)
y2=train_data['class']

# EDA for Test Data

In [31]:
#converting Class to numericals
test_df['class']=test_df['class'].map({'neg':0,'pos':1})

In [32]:
#removing and replacing na with np.NaN:
test_df.replace(to_replace='na',value=np.NaN,inplace=True)

In [36]:
test_df.shape

(16000, 162)

In [34]:
test_df=test_df.dropna(axis=1,thresh=9600) #Dropping column which don't have atleast 60% of data or 40% of NaN

In [103]:
test_x1=test_df.drop(['class'],1)
test_y1=test_df['class']

In [104]:
#imputation:
from sklearn.preprocessing import Imputer
test_impute_median = Imputer(missing_values= np.nan, strategy='median')
test_data = pd.DataFrame(test_impute_median.fit_transform(test_x1),columns=test_x1.columns)

C:\Users\Arun\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [105]:
test_data['class']=test_y1

In [106]:
test_x2=test_data.drop(['class'],1)
test_y2=test_data['class']

# Oversampling

In [13]:
xresampled, yresampled = SMOTE().fit_resample(x2, y2)

In [16]:
df1=pd.DataFrame(xresampled,columns=x2.columns)

In [17]:
df1['class']=yresampled

In [18]:
df1.head()

aa_000        ac_000  ad_000  ae_000  af_000  ag_000  ag_001  ag_002  \
0  76698.0  2.130706e+09   280.0     0.0     0.0     0.0     0.0     0.0   
1  33058.0  0.000000e+00   126.0     0.0     0.0     0.0     0.0     0.0   
2  41040.0  2.280000e+02   100.0     0.0     0.0     0.0     0.0     0.0   
3     12.0  7.000000e+01    66.0     0.0    10.0     0.0     0.0     0.0   
4  60874.0  1.368000e+03   458.0     0.0     0.0     0.0     0.0     0.0   

   ag_003   ag_004  ...      ee_003    ee_004    ee_005    ee_006    ee_007  \
0     0.0  37250.0  ...    493384.0  721044.0  469792.0  339156.0  157956.0   
1     0.0  18254.0  ...    178064.0  293306.0  245416.0  133654.0   81140.0   
2     0.0   1648.0  ...    159812.0  423992.0  409564.0  320746.0  158022.0   
3   318.0   2212.0  ...        46.0      58.0      44.0      10.0       0.0   
4     0.0  43752.0  ...    229790.0  405298.0  347188.0  286954.0  311560.0   

     ee_008  ee_009  ef_000  eg_000  class  
0   73224.0     0.0     0.0     0.0      0  
1   97576.0  1500.0     0.0     0.0      0  
2   95128.0   514.0     0.0     0.0      0  
3       0.0     0.0     4.0    32.0      0  
4  433954.0  1218.0     0.0     0.0      0  

[5 rows x 162 columns]

# RandomSampling

In [24]:
df_list=df1.values.tolist()

df_random=random.sample(df_list, 65000)

df_ran=pd.DataFrame(df_random,columns=df1.columns)

df_ran['class'].value_counts()

df_ran['class']=df_ran['class'].astype('int')

df_ran['class']=df_ran['class'].astype('category')

df_ran['class'].dtype

CategoricalDtype(categories=[0, 1], ordered=False)

In [25]:
df_ran.head()

aa_000         ac_000        ad_000  ae_000  af_000      ag_000  \
0  265024.127574  161956.205810  36336.834978     0.0     0.0  195.636927   
1   38634.000000     516.000000    450.000000     0.0     0.0    0.000000   
2       8.000000       0.000000     14.000000     0.0     0.0    0.000000   
3  883915.142909     625.747653    562.008433     0.0     0.0    0.000000   
4  353978.192860     152.000000    126.000000     0.0     0.0    0.000000   

         ag_001         ag_002        ag_003        ag_004  ...    \
0  41388.823056  616929.443280  2.633618e+06  8.405323e+06  ...     
1      0.000000       0.000000  4.300000e+02  1.561340e+05  ...     
2      0.000000       0.000000  0.000000e+00  6.000000e+00  ...     
3    970.781207   92203.631475  1.141712e+06  7.124907e+06  ...     
4  25324.150828  720982.231536  6.590343e+06  1.562477e+07  ...     

         ee_003        ee_004        ee_005        ee_006        ee_007  \
0  5.694000e+05  9.285491e+05  8.162699e+05  9.209207e+05  7.969670e+05   
1  2.353860e+05  4.398880e+05  3.189980e+05  1.753960e+05  1.103400e+05   
2  8.000000e+00  2.400000e+01  4.000000e+01  7.600000e+01  0.000000e+00   
3  6.001728e+05  1.028918e+06  1.434498e+06  2.836145e+06  4.049386e+06   
4  1.545911e+06  3.388010e+06  4.690092e+06  6.804886e+05  2.122490e+05   

         ee_008      ee_009  ef_000  eg_000  class  
0  46370.064926   27.192297     0.0     0.0      1  
1  82492.000000  172.000000     0.0     0.0      0  
2      0.000000    0.000000     0.0     0.0      0  
3  10816.764341    0.000000     0.0     0.0      1  
4   3557.629514    0.000000     0.0     0.0      1  

[5 rows x 162 columns]

In [27]:
df_ran['class'].value_counts()

0    32538
1    32462
Name: class, dtype: int64

In [28]:
x3=df_ran.drop(['class'],1)
y3=df_ran['class']

In [29]:
sc=StandardScaler()
x3=sc.fit_transform(x3)

In [30]:
from sklearn.model_selection import train_test_split

In [75]:
xtrain,xtest,ytrain,ytest=train_test_split(x3,y3,test_size=0.2,random_state=0)

In [42]:
dt=DecisionTreeClassifier()
lr=LogisticRegression()
rf=RandomForestClassifier()

In [76]:
dt.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [77]:
lr.fit(xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [78]:
rf.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [56]:
params={'max_depth':np.arange(1,20),'criterion':['entropy','gini']}
gs=GridSearchCV(dt,params,cv=5,scoring='recall')
gs.fit(x3,y3)
gs.best_params_

{'criterion': 'entropy', 'max_depth': 18}

In [57]:
dt_reg=DecisionTreeClassifier(criterion='entropy',max_depth=18,random_state=20)
lr_reg=LogisticRegression(penalty='l1',random_state=20)

# Without PCA

In [168]:
tc=[]
kf=KFold(n_splits=10,shuffle=True,random_state=20)
for name, model in zip(['dt','dt_reg','lR','Logistic_Reg','RF'],
                      [dt,dt_reg,lr,lr_reg,rf]):
    for train,test in kf.split(x3,y3):
        xtrain,xtest=x3[train,:],x3[test,:]
        ytrain,ytest=y3[train],y3[test]
        model.fit(xtrain,ytrain)
        ypred_model=model.predict(xtest)
        conf1=metrics.confusion_matrix(ytest,ypred_model)
        fp=conf1[0,1]
        fn=conf1[1,0]
        total_cost=(10*fp)+(500*fn)
        acc=metrics.accuracy_score(ytest,ypred_model)
    tc.append([name,total_cost,acc])
print(tc)

C:\Users\Arun\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Arun\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Arun\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Arun\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Arun\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", Conve

[['dt', 42880, 0.9895384615384616], ['dt_reg', 44350, 0.9909230769230769], ['lR', 110500, 0.9653846153846154], ['Logistic_Reg', 110990, 0.965076923076923], ['RF', 36510, 0.9953846153846154]]


In [107]:
test_x2=sc.transform(test_x2)

In [108]:
rf_ypred1=rf.predict(test_x2)
conf5=metrics.confusion_matrix(test_y2,rf_ypred1)
conf5

array([[   40, 15585],
       [   12,   363]], dtype=int64)

In [112]:
test_x2.shape

(16000, 161)

In [111]:
test_y2.shape

(16000,)

# Random Samping from test data

In [113]:
df7=pd.DataFrame(test_x2,columns=test_x1.columns)
df7['class']=test_y2

In [130]:
#since rf is not good: requires more training
df_list1=df7.values.tolist()

df_random1=random.sample(df_list1,9600)

df_ran1=pd.DataFrame(df_random1,columns=df1.columns)


In [132]:
df_ran1['class'].value_counts()

0.0    9397
1.0     203
Name: class, dtype: int64

In [133]:
df_ran1['class']=df_ran1['class'].astype('int')

df_ran1['class']=df_ran1['class'].astype('category')

df_ran1['class'].dtype

CategoricalDtype(categories=[0, 1], ordered=False)

In [136]:
x_train_ran=df_ran1.drop(['class'],1)
y_train_ran=df_ran1['class']

In [139]:
x_train_ran=sc.fit_transform(x_train_ran)

In [140]:
xtrain2=np.vstack((xtrain,x_train_ran))

In [148]:
xtrain2.shape

(68100, 161)

In [152]:
ytrain2.shape

(68100,)

In [150]:
y_train_ran.shape

(9600,)

In [151]:
ytrain2=np.concatenate((ytrain,y_train_ran))

# Training 2

In [154]:
xtrain5,xtest5,ytrain5,ytest5=train_test_split(xtrain2,ytrain2,test_size=0.2,random_state=5)

In [153]:
rf2=RandomForestClassifier()

In [156]:
rf2.fit(xtrain5,ytrain5)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [157]:
ypred_training2=rf2.predict(xtest5)

In [158]:
conf_training2=metrics.confusion_matrix(ytest5,ypred_training2)
conf_training2

array([[7688,   59],
       [  49, 5824]], dtype=int64)

In [162]:
test_x2.shape

(16000, 161)

In [163]:
rf2_pred_check=rf2.predict(test_x2)

In [164]:
conf_test_data_training2=metrics.confusion_matrix(test_y2,rf2_pred_check)
conf_test_data_training2

array([[14789,   836],
       [   93,   282]], dtype=int64)

In [218]:
fp1=conf_test_data_training2[0,1]
fn1=conf_test_data_training2[1,0]
total_cost_final=(10*fp1)+(500*fn1)
#acc_final=metrics.accuracy_score(ytest,ypred_model)
total_cost_final

54860

In [216]:
roc_auc=[]
fpr,tpr,_=roc_curve(test_y2,rf2_pred_check)
roc_auc.append(auc(fpr,tpr))
print("AUC Score for Random Forest fully trained model: ",roc_auc)

AUC Score for Random Forest fully trained model:  [0.849248]


In [ ]:
#RF2 ARE THE BEST MODELS TILL NOW

In [174]:
dt_bag=BaggingClassifier(base_estimator=dt,n_estimators=15,random_state=0)

# Training accuracy and total cost for Dt, Bagged DT, Random Forest

In [215]:
tc=[]
kf=KFold(n_splits=10,shuffle=True,random_state=5)
for name, model in zip(['dt','dt_bag','RF'],
                      [dt,dt_bag,rf]):
    for train,test in kf.split(x3,y3):
        xtrain,xtest=x3[train,:],x3[test,:]
        ytrain,ytest=y3[train],y3[test]
        model.fit(xtrain,ytrain)
        ypred_model=model.predict(xtest)
        conf1=metrics.confusion_matrix(ytest,ypred_model)
        fp=conf1[0,1]
        fn=conf1[1,0]
        total_cost=(10*fp)+(500*fn)
        acc=metrics.accuracy_score(ytest,ypred_model)
    tc.append([name,total_cost,acc])
print(tc)

[['dt', 11550, 0.9881538461538462], ['dt_bag', 2910, 0.9929230769230769], ['RF', 4310, 0.994]]


In [182]:
dt_bag.fit(xtrain5,ytrain5)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
    

# Test Accuracy Bagged DT

In [183]:
bag_pred=dt_bag.predict(xtest5)

In [185]:
confusion=metrics.confusion_matrix(ytest5,bag_pred)
confusion

array([[7668,   79],
       [  39, 5834]], dtype=int64)

In [217]:
fp=confusion[0,1]
fn=confusion[1,0]
total_cost_bag_dt=(10*fp)+(500*fn)
print("Total cost when we use the BagDt model: ",total_cost_bag_dt)

Total cost when we use the BagDt model:  20290


In [187]:
bag_pred1=dt_bag.predict(test_x2)
confusion1=metrics.confusion_matrix(test_y2,bag_pred1)
confusion1

array([[12242,  3383],
       [   82,   293]], dtype=int64)

In [211]:
roc_auc=[]
from sklearn.metrics import roc_curve, auc
fpr,tpr,_=roc_curve(test_y2,bag_pred1)
roc_auc.append(auc(fpr,tpr))
print("AUC Score for Decision Tree bagged model: ",roc_auc)

AUC Score for Decision Tree bagged model:  [0.7824106666666667]


In [198]:
gbs=GradientBoostingClassifier(n_estimators=100)

In [199]:
gbs.fit(xtrain5,ytrain5)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [200]:
gbs_pred1=gbs.predict(test_x2)
confusion_bag=metrics.confusion_matrix(test_y2,gbs_pred1)
confusion_bag

array([[9501, 6124],
       [   0,  375]], dtype=int64)

In [206]:
from sklearn.ensemble import VotingClassifier
stacked=VotingClassifier(estimators= [('RF',rf2),('baggeddt',dt_bag),('Gboost',gbs)],voting='soft')

In [207]:
stacked.fit(xtrain5,ytrain5)

VotingClassifier(estimators=[('RF',
                              RandomForestClassifier(bootstrap=True,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                                     max_features='auto',
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     n_estimators=10,
                                                     n_jobs=None,
           

In [208]:
stacked_pred1=stacked.predict(test_x2)
confusion_stack=metrics.confusion_matrix(test_y2,stacked_pred1)
confusion_stack

array([[12027,  3598],
       [    8,   367]], dtype=int64)

In [210]:
roc_auc=[]
from sklearn.metrics import roc_curve, auc
fpr,tpr,_=roc_curve(test_y2,stacked_pred1)
roc_auc.append(auc(fpr,tpr))
print("AUC Score for stacked model: ",roc_auc)

AUC Score for stacked model:  [0.8741973333333334]


In [214]:
fp=confusion_stack[0,1]
fn=confusion_stack[1,0]
total_cost=(10*fp)+(500*fn)
print("Total cost when we use the stacked model: ",total_cost)

Total cost when we use the stacked model:  39980


# Top Picks:

In [219]:
results=pd.DataFrame({'Model':['Stacked','Bagged Decision Tree','Random Forest(fully trained)'],'AUC':['87%','78%','84%'],'Total Cost':['39,980','20,290','54,860']})
results

Model  AUC Total Cost
0                       Stacked  87%     39,980
1          Bagged Decision Tree  78%     20,290
2  Random Forest(fully trained)  84%     54,860

## Among the top picks stacked model is the best because True Negative(that is missing one truck having APS problem is very less) and FP is relatively low.